language: elixir

elixir:
  - 1.7

otp_release:
  - 20.0
  - 21.0
  
env: MIX_ENV=test

sudo: false # faster builds

script:
  - mix compile --warnings-as-errors
  - mix test --cover
  - mix benchmark
  - mix format --check-formatted